[package]
name = "regchest"
version = "0.1.0"
edition = "2024"

[features]
default = ["funded_orchard_mobileclient"]
funded_orchard_mobileclient = []
funded_orchard_with_3_txs_mobileclient = []
funded_orchard_sapling_transparent_shielded_mobileclient = []
funded_transparent_mobileclient = []

[dependencies]
zingolib = { git = "https://github.com/zingolabs/zingolib.git", default-features = true, tag = "2.0.9", features = [
    "testutils",
] }
zingolib_testutils = { git = "https://github.com/zingolabs/zingolib", tag = "2.0.9", features = ["test_lwd_zcashd"] }

tokio = "1"

[patch.crates-io]
zcash_client_backend = { git = "https://github.com/zcash/librustzcash", rev = "3ba772c9b8"}
zcash_address = { git = "https://github.com/zcash/librustzcash", rev = "3ba772c9b8"}
zcash_keys = { git = "https://github.com/zcash/librustzcash", rev = "3ba772c9b8"}
zcash_primitives = { git = "https://github.com/zcash/librustzcash", rev = "3ba772c9b8"}
zcash_protocol = { git = "https://github.com/zcash/librustzcash", rev = "3ba772c9b8"}
zcash_transparent = { git = "https://github.com/zcash/librustzcash", rev = "3ba772c9b8"}

[profile.release]
debug = false

[profile.test]
opt-level = 3
debug = false
