[package]
name = "regchest"
version = "0.1.0"
edition = "2024"

[features]
default = ["funded_orchard_mobileclient"]
funded_orchard_mobileclient = []
funded_orchard_with_3_txs_mobileclient = []
funded_orchard_sapling_transparent_shielded_mobileclient = []
funded_transparent_mobileclient = []

[dependencies]
zingolib = { git = "https://github.com/zingolabs/zingolib.git", default-features = true, tag = "zingolib_v2.1.2", features = [
    "testutils",
] }
zingolib_testutils = { git = "https://github.com/zingolabs/zingolib", tag = "zingolib_v2.1.2", features = ["test_lwd_zcashd"] }

tokio = "1"

rusqlite = { version = "0.37.0", features = ["bundled"] }

[profile.release]
debug = false

[profile.test]
opt-level = 3
debug = false
